betaz/betaz/users/urls.py
from django.urls import path

from betaz.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view, user_ranking_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("rankings/top/", view=user_ranking_view, name="rankings")
]

betaz/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("betaz.users.urls", namespace="users")),
    path("events/", include("events.urls", namespace="events")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

betaz/events/urls.py
from django.urls import path
from .views import event_list_view, event_detail_view, user_bet_view, cancel_bet_view

app_name = "events"
urlpatterns = [
    path("", view=event_list_view, name="list"),
    path("<int:pk>/", view=event_detail_view, name="detail"),
    path("<int:pk>/bet", view=user_bet_view, name="bet"),
    path("<int:pk>/bet/<int:bet_pk>/cancel", view=cancel_bet_view, name="cancel-bet"),
]

betaz/betaz/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for betaz."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

betaz/events/models.py
from django.db import models

from betaz.users.models import User


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Team(BaseModel):
    name = models.CharField(max_length=128, unique=True, null=False, blank=False)
    logo_url = models.CharField(max_length=512, null=True, blank=True)

    def __str__(self):
        return self.name

PLAYER_ROLE_CHOICES = (
    ('owner', 'Owner'),
    ('captain', 'Captain'),
    ('member', 'Member')
)


class Player(BaseModel):
    name = models.CharField(max_length=512, unique=True, null=False, blank=False)
    team = models.OneToOneField(Team, on_delete=models.SET_NULL, null=True, blank=True)
    role = models.CharField(max_length=64, choices=PLAYER_ROLE_CHOICES, default='member')

    def __str__(self):
        return self.name + ' -- ' + str(self.team) if self.team else ''


EVENT_STATUS_CHOICES = (('not_started', 'Not Started'),
                                             ('on_going', 'On Going'),
                                             ('completed', 'Completed'),
                                             ('cancelled', 'Cancelled'))


class Event(BaseModel):
    name = models.CharField(max_length=512, null=False, blank=False)
    date_time = models.DateTimeField(null=True, blank=True)
    sport = models.CharField(max_length=512, default="", null=True, blank=True)
    description = models.CharField(max_length=1024, default="", null=True, blank=True)
    winning_team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True)
    match_drawn = models.BooleanField(null=True, blank=True)
    betting_closed = models.BooleanField(null=True, blank=True)
    event_status = models.CharField(max_length=64,
                                    choices=EVENT_STATUS_CHOICES,
                                    default='not_started')

    class Meta:
        ordering = ['-date_time']
    def display_event_status(self):
        return dict(EVENT_STATUS_CHOICES)[self.event_status]

    def __str__(self):
        return self.name + ' ' + self.sport if self.sport else '' + ' on ' + str(self.date_time) if self.date_time else ''


class EventTeam(BaseModel):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        unique_together = ('event', 'team')

    def __str__(self):
        return self.team.name if self.team else '' + ' -- ' + self.event.name


class EventPlayer(BaseModel):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        unique_together = ('event', 'player')

    def __str__(self):
        return (self.player.name + ' -- ' + self.player.team.name) if self.player else '' + ' ' + self.event.name


class EventOdds(BaseModel):
    event = models.OneToOneField(Event, on_delete=models.CASCADE)
    odd_type = models.CharField(max_length=64, choices=(('fixed', 'Fixed Odds'), ('pool', 'Pool Betting')), default='pool')
    team1 = models.ForeignKey(Team, related_name='team1', on_delete=models.SET_NULL, null=True, blank=True)
    team1_odds = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    team2 = models.ForeignKey(Team, related_name='team2', on_delete=models.SET_NULL, null=True, blank=True)
    team2_odds = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    draw_odds = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)

    class Meta:
        unique_together = ('event', 'team1', 'team2')

    def __str__(self):
        event_name = self.event.name if self.event else ''
        team1_name = self.team1.name if self.team1 else ''
        team2_name = self.team2.name if self.team2 else ''
        team1_odds = str(self.team1_odds) if self.team1_odds else ''
        team2_odds = str(self.team2_odds) if self.team2_odds else ''
        draw_odds = str(self.draw_odds) if self.draw_odds else ''
        return event_name + ' ' + self.odd_type + ' ' + team1_name + ': ' + team1_odds + ' ' + team2_name + ': ' + team2_odds + ' Draw Odds: ' + draw_odds


class UserBet(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    bet_on_team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)
    bet_on_draw = models.BooleanField(null=True, blank=True)
    bet_amount = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)
    is_settled = models.BooleanField(default=False)

    class Meta:
        unique_together = ('user', 'event')

    def __str__(self):
        user_name = self.user.name if self.user else ''
        event_name = self.event.name if self.event else ''
        team_name = 'On ' + self.bet_on_team.name if self.bet_on_team else 'On Draw' if self.bet_on_draw else ''
        amount = str(self.bet_amount) if self.bet_amount else ''
        return user_name + ' -- ' + event_name + ' -- ' + team_name + ' -- AZ' + amount


class UserWallet(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    money = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.user.name + ' -- AZ' + str(self.money)


class UserRanking(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    amount_won = models.DecimalField(max_digits=14, decimal_places=2, null=True, blank=True)

betaz/betaz/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

betaz/betaz/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

betaz/betaz/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView, ListView

from events.models import UserWallet, UserBet

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class UserRankingView(ListView):
    model = UserWallet
    template_name = 'users/ranking_list.html'

    def get_queryset(self) -> QuerySet:
        betting_user_ids = list(UserBet.objects.all().values_list('user_id', flat=True))
        return UserWallet.objects.filter(user_id__in=betting_user_ids)

    class Meta:
        ordering = ['-money']


user_ranking_view = UserRankingView.as_view()

betaz/events/views.py
import logging
from decimal import Decimal
from typing import Any, Dict

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView

User = get_user_model()
from .models import Event, UserBet, Team, UserWallet, EventOdds

log = logging.getLogger(__name__)


class EventListView(ListView):
    model = Event


event_list_view = EventListView.as_view()


class EventDetailView(LoginRequiredMixin, DetailView):
    model = Event

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        event = self.get_object()
        context['bet'] = event.userbet_set.filter(user__username=self.request.user.username).first()
        teams = list()
        team1_players = list()
        team2_players = list()
        if event.eventteam_set.exists():
            for event_team in event.eventteam_set.iterator():
                teams.append(event_team.team)

        if len(teams) >= 2:
            context['team1'] = teams[0]
            if event.eventplayer_set.filter(player__team=teams[0]).exists():
                team1_players = list(event.eventplayer_set.filter(player__team=teams[0]))
            context['team1_players'] = team1_players
            context['team2'] = teams[1]
            if list(event.eventplayer_set.filter(player__team=teams[1])):
                team2_players = list(event.eventplayer_set.filter(player__team=teams[1]))
            context['team2_players'] = team2_players
        else:
            context['team1'] = None
            context['team2'] = None

        context['teams'] = teams
        event_odds = None
        try:
            event_odds = event.eventodds
        except EventOdds.DoesNotExist:
            log.warning("EventOdds do not exist for this event")
        context['event_odds'] = event_odds
        return context


event_detail_view = EventDetailView.as_view()


class UserBetView(View):

    def post(self, request, pk):
        data = request.POST
        event = Event.objects.get(pk=pk)
        auth_user = request.user
        user = User.objects.get(username=auth_user.username)
        user_wallet = UserWallet.objects.get(user=user)

        user_bet = UserBet.objects.filter(user=user, event=event).first()
        if user_bet:
            bet_amount = user_bet.bet_amount
            user_wallet.money = F('money') + bet_amount
            user_wallet.save()
            user_bet.delete()
        user_bet = UserBet()
        user_bet.user = user
        user_bet.event = Event.objects.get(pk=pk)
        if user_bet.is_settled:
            messages.info(request, 'Bet already settled!')
        else:
            if data["team"] != "Draw":
                user_bet.bet_on_team = Team.objects.get(pk=data['team'])
            else:
                user_bet.bet_on_team = None
                user_bet.bet_on_draw = True
            user_wallet.money = F('money') - Decimal(data['amount'])
            user_wallet.save()
            user_bet.bet_amount = data['amount']
            user_bet.save()
            messages.info(request, 'Bet Added! All the best.')
        return HttpResponseRedirect(reverse('events:detail', args=(pk,)))


user_bet_view = UserBetView.as_view()


class CancelBetView(View):

    def get(self, request, pk, bet_pk):
        user_bet = UserBet.objects.get(pk=bet_pk)
        auth_user = request.user
        user = User.objects.get(username=auth_user.username)
        user_wallet = UserWallet.objects.get(user=user)
        if user_bet.user.username == auth_user.username:
            bet_amount = user_bet.bet_amount
            user_wallet.money = F('money') + bet_amount
            user_wallet.save()
            user_bet.delete()
            messages.info(request, 'Bet Cancelled!')
        else:
            messages.warning(request, 'Cannot cancel this bet!')

        return HttpResponseRedirect(reverse('events:detail', args=(pk,)))


cancel_bet_view = CancelBetView.as_view()

betaz/betaz/templates/events/event_detail.html
{% extends "base.html" %}
{% load static %}
{% load mathfilters %}

{% block title %}Events{% endblock %}
{% block content %}

<div class="container">
<!--  Event title-->
  <div class="row">
    <div class="col"></div>
    <div class="col-10">
      <h2 class="text-center">{{ object.name }}</h2>
    </div>
    <div class="col"></div>
  </div>

<!--  Sport and DateTime-->
  <div class="row">
    <div class="col"></div>
    <div class="col-10">
      <h5 class="text-center">{{ object.sport }} on {{ object.date_time|date:'D d M h:i a' }}</h5>
    </div>
    <div class="col"></div>
  </div>

<!--  Team vs Team-->
  <div class="row">
    <div class="col-5">
      <img src="{% static 'images/team_logos/' %}{{team1.logo_url}}" alt="{{ team1.name }}" style="max-width: 75%; max-height:75%;" class="mx-auto d-block">
    </div>
    <div class="col">
      <div class="d-block"><h4 class="text-center">vs</h4></div>
    </div>
    <div class="col-5">
      <img src="{% static 'images/team_logos/' %}{{team2.logo_url}}" alt="{{ team1.name }}" style="max-width: 75%; max-height:75%;" class="mx-auto d-block">
    </div>
  </div>

<!--  Players-->
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <div class="d-flex list-group justify-content-center">
        {% for player in team1_players %}
        <div class="list-group-item"><div class="text-center">{{ player.player.name }}</div></div>
        {% empty %}
          <div class="list-group-item"><div class="text-center">No players yet.</div></div>
        {% endfor %}
      </div>
    </div>
    <div class="col">
      {% if object.event_status == 'completed' %}
        {% if object.match_drawn is not None and object.match_drawn is True %}
          <div class="text-center"><h4>Match was a draw!</h4></div>
        {% else %}
          <div class="text-center"><h4>{{ object.winning_team }} won!</h4></div>
        {% endif%}
      {% elif object.event_status == 'cancelled' %}
        <div class="text-center"><h4>Match cancelled!</h4></div>
      {% else %}
      {% endif %}
    </div>
    <div class="col-3">
      <div class="d-flex list-group justify-content-center">
        {% for player in team2_players %}
        <div class="list-group-item"><div class="text-center">{{ player.player.name }}</div></div>
        {% empty %}
          <div class="list-group-item"><div class="text-center">No players yet.</div></div>
        {% endfor %}
      </div>
    </div>
    <div class="col-1"></div>
  </div>
</div>

  {% if event_odds is not None %}
  <!--Betting Odds title-->
      <div class="row">
        <div class="col">
          <div class="text-center"><h3 style="margin-top:5%;">Betting Odds</h3></div>
        </div>
      </div>
  <!--Betting Odds-->
      <div class="row" style="margin-top:2.5%;">
        <div class="col-1"></div>
        <div class="col-3">
          <div class="text-center"><h5>{{ object.eventodds.team1_odds }}</h5></div>
          <div class="text-center font-weight-lighter small">AZ{{ object.eventodds.team1_odds|mul:100 }} on AZ100.00 if {{ object.eventodds.team1 }} wins!</div>
        </div>
        <div class="col">
          <div class="text-center"><h5>{{ object.eventodds.draw_odds }}</h5></div>
          <div class="text-center font-weight-lighter small">AZ{{ object.eventodds.draw_odds|mul:100 }} on AZ100.00 if match draws!</div>
        </div>
        <div class="col-3">
          <div class="text-center"><h5>{{ object.eventodds.team2_odds }}</h5></div>
          <div class="text-center font-weight-lighter small">AZ{{ object.eventodds.team2_odds|mul:100 }} on AZ100.00 if {{ object.eventodds.team2 }} wins!</div>
        </div>
        <div class="col-1"></div>
      </div>
  {% else %}
  <!--Betting Odds title-->
      <div class="row">
        <div class="col">
          <div class="text-center"><h3 style="margin-top:5%;">Betting Odds Not Available</h3></div>
        </div>
      </div>
  {% endif %}


  {% if not object.betting_closed %}
    <!--Place bet title-->
    {% if bet.is_settled %}
      <div class="row">
        <div class="col">
          <div class="text-center"><h3 style="margin-top:5%;">Bet Placed</h3></div>
        </div>
      </div>
    {% else %}
      <div class="row">
        <div class="col">
          <div class="text-center"><h3 style="margin-top:5%;">Place Bet</h3></div>
        </div>
      </div>
    {% endif %}
      <!--Place bet form-->
      <div class="row" style="margin-top:2.5%;">
          <div class="col">
            <form method="post" action="/events/{{ object.pk }}/bet">
              {% csrf_token %}
              <fieldset {% if bet.is_settled %}disabled{% endif %}>
                <div class="form-row">
                  <div class="col-4">
                    <div class="form-group">
                    <select name="team" class="form-control">
                      {% if bet is None %}
                        <option value="" disabled selected>Select Team</option>
                        <option value="Draw">Draw</option>
                        {% for team in teams %}
                          <option name={{team.name}} value={{team.id}}>{{team.name}}</option>
                        {% endfor %}
                      {% else %}
                        <option value="Draw" {% if bet.bet_on_draw %} selected {% endif %}>Draw</option>
                        {% for team in teams %}
                          <option name={{team.name}} value={{team.id}} {% if bet.bet_on_team.id == team.id %} selected {% endif %}>{{team.name}}</option>
                        {% endfor %}
                      {% endif %}
                    </select>
                  </div>
                  </div>
                  <div class="col-8">
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="bet-amount">AZ</span>
                      </div>
                      <input type="number" name="amount" class="form-control" placeholder="Enter amount..." aria-label="Amount" aria-describedby="bet-amount" value="{{bet.bet_amount}}">
                    </div>
                  </div>
                </div>
                <div class="form-row">
                  <div class="col">
                    <div class="text-right">
                      <div class="btn-group" role="group">
                        {% if bet is not None %}
                          <a class="btn btn-danger" role="button" href="{% url 'events:cancel-bet' event.id bet.id %}">Cancel Bet</a>
                          <input class="btn btn-primary" type="submit" value="Update Bet">
                        {% else %}
                          <input class="btn btn-primary" type="submit" value="Place Bet">
                        {% endif %}


                      </div>
                    </div>
                  </div>
                </div>
              </fieldset>

            </form>
          </div>
        </div>
  {% else %}
    {% if bet is not None %}
    <!--Place bet title-->
      <div class="row">
        <div class="col">
          {% if bet.bet_on_draw %}
            <div class="text-center"><h3 style="margin-top:5%;">AZ{{ bet.bet_amount }} bet on Draw</h3></div>
          {% else %}
            <div class="text-center"><h3 style="margin-top:5%;">AZ{{ bet.bet_amount }} bet on {{ bet.bet_on_team.name }}</h3></div>
          {% endif %}
        </div>
      </div>
    {% else %}
      <div class="row">
        <div class="col">
            <div class="text-center"><h3 style="margin-top:5%;">You did not place bet on this event</h3></div>
        </div>
      </div>
    {% endif %}
  {% endif %}
{% endblock content %}

betaz/betaz/templates/events/event_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Events{% endblock %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <h3>Events</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">On</th>
              <th scope="col">Sport</th>
              <th scope="col">Winner</th>
              <th scope="col">Draw</th>
              <th scope="col">Betting Closed</th>
              <th scope="col">Status</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for event in object_list %}
              <tr>
                <td><div class="text-left">{{ event.name }}</div></td>
                <td><div class="text-left">{% if event.date_time is not None %}{{ event.date_time|date:'D d M h:i a' }} {% else %} - {% endif %} </div></td>
                <td><div class="text-left">{% if event.date_time is not None %}{{ event.sport }} {% else %} - {% endif %}</div></td>
                <td><div class="text-center">{% if event.winning_team is not None %}{{ event.winning_team }} {% else %} - {% endif %}</div></td>
                <td><div class="text-center">{% if event.match_drawn is not None %}{{ event.match_drawn|yesno:"Yes, No" }} {% else %} - {% endif %}</div></td>
                <td><div class="text-center">{{ event.betting_closed|yesno:"Yes,No" }}</div></td>
                <td><div class="text-left">{% if event.event_status is not None %}{{ event.display_event_status }} {% else %} - {% endif %}</div></td>
                {% if event.betting_closed %}
                  <td><div><a class="btn btn-outline-primary btn-sm" href="{% url 'events:detail' event.id %}">View</a></div></td>
                {% else %}
                  <td><div><a class="btn btn-primary btn-sm" href="{% url 'events:detail' event.id %}">Bet</a></div></td>
                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}